version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: qwedsaqwe
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: testuser
      DB_PASS: test
      DB_NAME: mysql_db
      DB_TABLE_NAME: devicemovingview
      site: localhost
    command: node app.js
    ports:
      - '80:3000'
    depends_on:
      - db
    restart: on-failure
